### ISSUE TITLE
Fade effect doesn't work with Firefox 34.0.5

### ISSUE THREAD

**Issue by traverse** [sorrentix/scrollie#1]
Saw your post on css-tricks and had a look. I noticed however that the fade effect isn't working in Firefox for me not sure what the issue is since you've prefixed the css animations. Might be worth looking into!

Kind regards,
Trav

**Comment by sorrentix** [comment]
Thanks for pointing out the issue. I think I solved it. Not sure about the problem, just a matter of sintax in javascript. I changed style["animation-duration"] to style.animationDuration and it seems to work now.
Thanks again =) 
Andrea

**Comment by traverse** [comment]
No problem, glad you were able to resolve the issue :)

Kind regards,

Tom
